# Generated by Django 5.0.2 on 2024-02-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandestage',
            old_name='datecurent',
            new_name='dates',
        ),
    ]
