# Generated by Django 5.0.2 on 2024-03-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandestage',
            name='fichier',
            field=models.ImageField(upload_to='media'),
        ),
    ]
