# Generated by Django 5.0.2 on 2024-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_demandestage_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandestage',
            name='fichier',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
