# Generated by Django 5.0.2 on 2024-03-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_demandestage_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandestage',
            name='fichier',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
